set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin indent on

" open help vertically
command! -nargs=* -complete=help Help vertical belowright help <args>
autocmd FileType help wincmd L

" Builtins
luafile $HOME/.config/nvim/lua/settings/init.lua
luafile $HOME/.config/nvim/lua/lsp/init.lua
" Plugins
luafile $HOME/.config/nvim/lua/statusline/init.lua
luafile $HOME/.config/nvim/lua/treesitter/init.lua
luafile $HOME/.config/nvim/lua/fugitive/init.lua
luafile $HOME/.config/nvim/lua/fzf/init.lua
luafile $HOME/.config/nvim/lua/dirvish/init.lua
luafile $HOME/.config/nvim/lua/better_whitespace/init.lua
" Languages
luafile $HOME/.config/nvim/lua/terraform/init.lua
luafile $HOME/.config/nvim/lua/json/init.lua
luafile $HOME/.config/nvim/lua/nginx/init.lua
luafile $HOME/.config/nvim/lua/yml/init.lua
luafile $HOME/.config/nvim/lua/md/init.lua
luafile $HOME/.config/nvim/lua/txt/init.lua
luafile $HOME/.config/nvim/lua/vim/init.lua
luafile $HOME/.config/nvim/lua/tmux/init.lua
luafile $HOME/.config/nvim/lua/nix/init.lua
